version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1938:1938"
    expose:
      - "1938"
    links:
      - db
    volumes:
      - .:/app
    command: tail -f /dev/null

  db:
      image: mdillon/postgis:10
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - '5432:5432'
      volumes:
        - ./.data/dbpgdata:/var/lib/postgresql/data